### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by DaveBlooman** [vimeo/graphite-api-influxdb-docker#2]
Hi,

Im using the tutum/influx container with graphite-api-influxdb-docker.  When accessing influxdb directly via Grafana, the data is returned.  When using graphite-api-influxdb, the API is available, but it doesn't seem to connect to influxdb.  Here is the way i'm setting up the containers.

```sh
docker run -d -p 8083:8083 -p 8086:8086 \
                      -p 2003:2003 -p 2004:2004 \
                      -p 7002:7002 -p 8084:8084 \
                      -e PRE_CREATE_DB="graphite; grafana" --name db tutum/influxdb

docker run -it -p 8000:8000 --link db:influx influx-docker
```

graphite-api.yaml

```yaml
search_index: /srv/graphite/index
finders:
  - graphite_influxdb.InfluxdbFinder
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
influxdb:
   host: influx
   port: 8086
   user: admin
   pass: admin
   db:   graphite
   ssl: false
   # be sure to update this to describe the resolutions of your metrics
   # see https://github.com/vimeo/graphite-influxdb#about-the-retention-schemas
   schema:
     - ['', 60]
     - ['high-res-metrics', 10]

whisper:
  directories:
    - /srv/graphite/whisper
time_zone: Europe/London
logging:
  version: 1
  disable_existing_loggers: true
  handlers:
    file:
      class: logging.FileHandler
      filename: /var/log/graphite-api.log
    stdout:
      class: logging.StreamHandler
  loggers:
    graphite_api:
      handlers:
        - stdout
      propagate: true
      level: INFO
    graphite_influxdb:
      handlers:
        - stdout
      propagate: true
      level: INFO
    root:
      handlers:
        - stdout
      propagate: true
      level: INFO
# sentry_dsn: <dsn>
cache:
    # memcache seems to have issues with storing the series. the data is too big and doesn't store it, and doesn't allow bumping size in config that much
    #type: 'memcached'
    #prefix: 'graphite_api'
    type: 'filesystem'
    dir: '/tmp/graphite-api-cache'

# remove statsd section to disable statsd integratio

allowed_origins:
    - '*'

```
